# -*- coding: utf-8 -*-
"""
Batch 2 - Chunk 1: SRC-09 Cryptography Short Questions (12 questions)
Q-SHORT-063 ~ Q-SHORT-074
"""

CHUNK_1_QUESTIONS = [
    {
        "id": "Q-SHORT-063",
        "type": "short",
        "category": "정보보안 일반 및 암호학",
        "score": 3,
        "question": "다음 설명에 해당하는 국내 표준 대칭키 블록 암호 알고리즘의 명칭을 영문 또는 국문으로 쓰시오.\n\n[설명]\n- 1999년 2월 한국인터넷진흥원(KISA)과 국내 암호 전문가들이 순수 국내 기술로 개발한 블록 암호 알고리즘이다.\n- 전자상거래, 금융, 무선통신 등에서 중요한 정보를 보호하기 위해 제정된 한국 정보통신 표준(TTAS.KO-12.0004)이다.\n- 블록 크기는 128비트이며, 128비트 비밀키를 사용하여 총 16라운드의 페이스텔(Feistel) 구조로 동작한다.",
        "answer": "SEED",
        "accepted_answers": ["SEED", "시드"],
        "grading_mode": "normalized",
        "explanation": "SEED는 1999년 KISA 주도로 개발된 128비트 블록 암호 알고리즘으로, 16라운드 Feistel 구조를 가집니다 (SRC-09 p.20).",
        "source_id": "SRC-09",
        "source_page": 20,
        "concept_id": "CON-CRY-01"
    },
    {
        "id": "Q-SHORT-064",
        "type": "short",
        "category": "정보보안 일반 및 암호학",
        "score": 3,
        "question": "다음 설명에 해당하는 경량 대칭키 블록 암호 알고리즘의 영문 약어를 쓰시오.\n\n[설명]\n- RFID 태그, USN 센서 노드 등 저전력·초경량화가 요구되는 컴퓨팅 환경에서 기밀성을 제공하기 위해 개발된 64비트 블록 암호이다.\n- KISA, ETRI 부설연구소, 고려대학교가 공동 개발하였으며, 128비트 비밀키를 사용하여 32라운드의 변형 페이스텔 구조로 동작한다.\n- 하드웨어 구현 시 게이트 수를 최소화하기 위해 단순한 덧셈, XOR, 시프트 연산만으로 설계되었다.",
        "answer": "HIGHT",
        "accepted_answers": ["HIGHT", "하이트"],
        "grading_mode": "normalized",
        "explanation": "HIGHT(HIGhsecurity and light weigHT)는 RFID/USN 등 초경량 환경을 위해 개발된 64비트 블록/128비트 키의 32라운드 변형 Feistel 암호입니다 (SRC-09 p.21).",
        "source_id": "SRC-09",
        "source_page": 21,
        "concept_id": "CON-CRY-01"
    },
    {
        "id": "Q-SHORT-065",
        "type": "short",
        "category": "정보보안 일반 및 암호학",
        "score": 3,
        "question": "다음 설명에 해당하는 국내 개발 고속 대칭키 블록 암호 알고리즘의 영문 약어를 쓰시오.\n\n[설명]\n- 빅데이터, 클라우드 등 고속 처리 환경 및 사물인터넷(IoT) 등 경량 환경에서 고속 암호화를 제공하기 위해 국가보안기술연구소(NSRI)가 개발한 128비트 블록 암호이다.\n- S-box를 사용하지 않고 ARX(Addition, Rotation, XOR) 연산만을 사용하여 소프트웨어 고속 구현에 최적화되었다.\n- 비밀키 길이는 128, 192, 256비트를 지원하며, AES 대비 약 1.5~2배 빠른 성능을 제공한다.",
        "answer": "LEA",
        "accepted_answers": ["LEA", "리아"],
        "grading_mode": "normalized",
        "explanation": "LEA(Lightweight Encryption Algorithm)는 국가보안기술연구소가 개발한 128비트 블록 암호로, S-box 없이 ARX 연산만을 사용하여 고속 암호화를 지원합니다 (SRC-09 p.22).",
        "source_id": "SRC-09",
        "source_page": 22,
        "concept_id": "CON-CRY-01"
    },
    {
        "id": "Q-SHORT-066",
        "type": "short",
        "category": "정보보안 일반 및 암호학",
        "score": 3,
        "question": "다음 설명에 해당하는 국내 국가 표준 대칭키 블록 암호 알고리즘의 영문 명칭을 쓰시오.\n\n[설명]\n- 국가보안기술연구소(NSRI) 주도로 학계(Academy), 연구소(Research Institute), 정부기관(Agency)이 공동 개발하여 한국 국가 표준(KS X 1213) 및 전자정부 표준으로 채택된 암호 알고리즘이다.\n- 128비트 블록 크기를 가지며, 128/192/256비트 키 길이에 따라 12/14/16라운드로 동작한다.\n- 입출력 구조가 동일하여 암호화와 복호화 과정이 동일한 인볼루션(Involutional) SPN 구조를 채택하여 하드웨어 구현 효율성을 극대화하였다.",
        "answer": "ARIA",
        "accepted_answers": ["ARIA", "아리아"],
        "grading_mode": "normalized",
        "explanation": "ARIA는 국가보안기술연구소가 개발한 Involutional SPN 구조의 128비트 블록 암호 알고리즘으로 KS X 1213 표준입니다 (SRC-09 p.24).",
        "source_id": "SRC-09",
        "source_page": 24,
        "concept_id": "CON-CRY-01"
    },
    {
        "id": "Q-SHORT-067",
        "type": "short",
        "category": "정보보안 일반 및 암호학",
        "score": 3,
        "question": "다음 설명이 가리키는 암호 기법의 명칭을 국문 또는 영문으로 쓰시오.\n\n[설명]\n- 버남(Vernam)이 고안한 스트림 암호 방식으로, 암호화를 수행할 때마다 평문과 동일한 길이의 완전한 무작위(난수) 키 스트림을 생성하여 평문과 1회 XOR 연산하여 암호화한다.\n- 한 번 사용된 키 스트림은 절대 재사용하지 않고 즉시 폐기한다.\n- 무한한 계산 능력을 가진 도청자라도 평문의 정보량을 얻을 수 없다는 '이론적으로 완전한 해독 불가능성(무조건적 안전성; Unconditional Security)'을 증명받은 유일한 암호 체계이다.",
        "answer": "일회용 패드",
        "accepted_answers": ["일회용 패드", "일회용패드", "OTP", "One Time Pad", "버남 암호", "Vernam"],
        "grading_mode": "normalized",
        "explanation": "일회용 패드(One Time Pad; Vernam)는 평문과 동일한 길이의 무작위 난수 키를 1회만 사용하여 XOR하는 방식으로 무조건적 안전성을 제공합니다 (SRC-09 p.27).",
        "source_id": "SRC-09",
        "source_page": 27,
        "concept_id": "CON-CRY-01"
    },
    {
        "id": "Q-SHORT-068",
        "type": "short",
        "category": "정보보안 일반 및 암호학",
        "score": 3,
        "question": "다음 설명에 해당하는 공개키 기반 키 교환 알고리즘의 명칭을 국문 또는 영문으로 쓰시오.\n\n[설명]\n- 1976년 휫필드 디피(Whitfield Diffie)와 마틴 헬만(Martin Hellman)이 제안한 최초의 공개키 기반 키 교환 프로토콜이다.\n- 사전에 비밀키를 공유하지 않은 두 당사자가 공개된 통신망을 통해 안전하게 동일한 비밀 대칭키를 공유할 수 있게 한다.\n- 수학적으로 유한체 상에서의 '이산대수 문제(Discrete Logarithm Problem)'의 계산 복잡도에 안전성을 두고 있다.\n- 프로토콜 자체에 상대방의 신원을 검증하는 상호 인증(Authentication) 기능이 없어 중간자 공격(Man-In-The-Middle Attack)에 취약하다.",
        "answer": "디피-헬만",
        "accepted_answers": ["디피-헬만", "디피 헬만", "Diffie-Hellman", "디피헬만", "DH"],
        "grading_mode": "normalized",
        "explanation": "디피-헬만(Diffie-Hellman) 키 교환 알고리즘은 이산대수 난이도에 기반하여 비밀키를 교환하는 방식으로, 인증 기능 부재로 중간자 공격에 취약합니다 (SRC-09 p.35).",
        "source_id": "SRC-09",
        "source_page": 35,
        "concept_id": "CON-CRY-01"
    },
    {
        "id": "Q-SHORT-069",
        "type": "short",
        "category": "정보보안 일반 및 암호학",
        "score": 3,
        "question": "다음 설명에 해당하는 공개키 암호 알고리즘의 영문 약어를 쓰시오.\n\n[설명]\n- 타원곡선 위의 점들의 연산 군(Group)에서 정의되는 '타원곡선 이산대수 문제(ECDLP)'의 난해성에 안전성의 기반을 둔 공개키 암호 알고리즘이다.\n- RSA나 기존 디피-헬만 방식에 비해 훨씬 짧은 키 길이(예: 256비트 키로 RSA 3072비트 수준의 동등 보안 강도 제공)를 갖는다.\n- 키 길이가 짧아 연산 속도가 빠르고 메모리와 대역폭 소모가 적어 스마트카드, 모바일 기기, IoT 환경에 적합하다.",
        "answer": "ECC",
        "accepted_answers": ["ECC", "타원곡선 암호", "타원곡선암호", "Elliptic Curve Cryptography"],
        "grading_mode": "normalized",
        "explanation": "ECC(Elliptic Curve Cryptography)는 타원곡선 이산대수 문제(ECDLP)를 기반으로 하여 RSA보다 훨씬 짧은 키 길이로 동일한 보안 강도를 제공합니다 (SRC-09 p.38).",
        "source_id": "SRC-09",
        "source_page": 38,
        "concept_id": "CON-CRY-01"
    },
    {
        "id": "Q-SHORT-070",
        "type": "short",
        "category": "정보보안 일반 및 암호학",
        "score": 3,
        "question": "암호학적 일방향 해시 함수가 만족해야 하는 3대 안전성 특성 중 다음 설명에 해당하는 특성의 명칭을 쓰시오.\n\n[설명]\n- 서로 다른 임의의 두 입력값 x와 x'에 대하여, 두 입력값의 해시 결과값이 동일한 경우(H(x) = H(x'), x ≠ x')를 찾아내는 것이 계산상 불가능해야 한다는 특성이다.\n- 이 특성이 깨지면 공격자가 서로 다른 두 메시지에 대해 동일한 디지털 서명을 생성하거나 서명을 위조할 수 있게 된다.",
        "answer": "충돌 저항성",
        "accepted_answers": ["충돌 저항성", "충돌저항성", "충돌 회피", "충돌회피", "Collision Resistance"],
        "grading_mode": "normalized",
        "explanation": "충돌 저항성(Collision Resistance)은 H(x) = H(x')를 만족하는 서로 다른 임의의 두 입력 x, x'를 찾기 어려워야 한다는 특성입니다 (SRC-09 p.50).",
        "source_id": "SRC-09",
        "source_page": 50,
        "concept_id": "CON-CRY-02"
    },
    {
        "id": "Q-SHORT-071",
        "type": "short",
        "category": "정보보안 일반 및 암호학",
        "score": 3,
        "question": "해시 함수의 충돌 가능성을 설명하는 기초적인 이산수학 원리로, 'n개의 비둘기집에 n + 1마리의 비둘기를 넣으면 적어도 하나의 비둘기집에는 2마리 이상의 비둘기가 들어간다'는 원리의 명칭을 쓰시오. 입력 데이터의 개수가 해시값의 전체 경우의 수보다 많을 경우 반드시 둘 이상의 입력 데이터가 동일한 해시값을 갖게 되는 해시 충돌의 근거가 된다.",
        "answer": "비둘기집 원리",
        "accepted_answers": ["비둘기집 원리", "비둘기집원리", "비둘기집", "Pigeonhole Principle"],
        "grading_mode": "normalized",
        "explanation": "비둘기집 원리(Pigeonhole Principle)는 입력 데이터 수가 해시값의 경우의 수보다 많을 때 반드시 해시 충돌이 발생함을 설명하는 원리입니다 (SRC-09 p.51).",
        "source_id": "SRC-09",
        "source_page": 51,
        "concept_id": "CON-CRY-02"
    },
    {
        "id": "Q-SHORT-072",
        "type": "short",
        "category": "정보보안 일반 및 암호학",
        "score": 3,
        "question": "다음 설명에 해당하는 분산 네트워크 인증 프로토콜의 명칭을 국문 또는 영문으로 쓰시오.\n\n[설명]\n- 사용자나 서비스가 안전하게 인증을 수행할 수 있도록 MIT에서 개발한 클라이언트-서버 기반의 중앙 집중형 인증 프로토콜이다.\n- 분산 컴퓨팅 환경에서 대칭키 암호를 기반으로 신뢰할 수 있는 제3자 인증 서비스를 제공한다.\n- 사용자가 한 번의 인증을 통해 여러 시스템에 접근할 수 있는 단일 로그인(SSO; Single Sign On) 기능을 제공한다.",
        "answer": "커버로스",
        "accepted_answers": ["커버로스", "Kerberos"],
        "grading_mode": "normalized",
        "explanation": "커버로스(Kerberos)는 MIT에서 개발한 대칭키 암호 기반의 중앙 집중형 인증 및 SSO 프로토콜입니다 (SRC-09 p.75).",
        "source_id": "SRC-09",
        "source_page": 75,
        "concept_id": "CON-CRY-03"
    },
    {
        "id": "Q-SHORT-073",
        "type": "short",
        "category": "정보보안 일반 및 암호학",
        "score": 3,
        "question": "다음 설명에 해당하는 모바일 및 웹 보안 기술의 명칭을 국문 또는 영문으로 쓰시오.\n\n[설명]\n- 클라이언트(모바일 앱 등)가 서버와 TLS/SSL 통신을 연결할 때, 신뢰된 공인 CA 목록 전체를 무조건 신뢰하지 않고 특정 서버 인증서의 공개키(또는 인증서 해시값)를 클라이언트 앱 내부에 직접 하드코딩하여 비교·검증하는 기술이다.\n- 공격자가 악성 루트 인증서를 클라이언트 단말에 강제 설치하여 프록시 기반으로 트래픽을 복호화하는 중간자 공격(MITM)이나 침해된 인증기관(CA)의 위조 인증서 발급 공격을 효과적으로 방어할 수 있다.",
        "answer": "인증서 핀닝",
        "accepted_answers": ["인증서 핀닝", "인증서핀닝", "인증서 고정", "인증서고정", "Certificate Pinning", "SSL Pinning"],
        "grading_mode": "normalized",
        "explanation": "인증서 핀닝(Certificate Pinning; 인증서 고정)은 클라이언트 내부에 서버 인증서나 공개키를 등록해두고 직접 검증하여 중간자 공격을 방어합니다 (SRC-09 p.122, 151).",
        "source_id": "SRC-09",
        "source_page": 122,
        "concept_id": "CON-CRY-02"
    },
    {
        "id": "Q-SHORT-074",
        "type": "short",
        "category": "정보보안 일반 및 암호학",
        "score": 3,
        "question": "PKI 환경에서 전자서명 인증서의 유효성을 실시간으로 확인하기 위한 프로토콜로, 주기적으로 배포되는 인증서 폐기 목록(CRL)을 다운로드할 때 발생하는 대역폭 낭비와 폐기 정보 반영 지연 문제를 해결하기 위해 고안된 표준 프로토콜의 영문 약어를 쓰시오.",
        "answer": "OCSP",
        "accepted_answers": ["OCSP", "Online Certificate Status Protocol", "온라인 인증서 상태 프로토콜"],
        "grading_mode": "normalized",
        "explanation": "OCSP(Online Certificate Status Protocol)는 인증서 폐기 여부를 실시간으로 서버에 질의하여 응답받는 프로토콜입니다 (SRC-09 p.142).",
        "source_id": "SRC-09",
        "source_page": 142,
        "concept_id": "CON-CRY-02"
    }
]
